# FIXME:
# compose for development

services:
  
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "templ", "generate", "--watch", "--proxy='http://localhost:8000'", "--cmd='go run .'" ]

    env_file: .env
    restart: on-failure:10
    container_name: ${CONT_NAME}
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: .
          target: /app

        - action: rebuild
          path: ./go.mod
